OLED_ENABLE = yes
ENCODER_ENABLE = yes       # Enables the use of one or more encoders
RGB_MATRIX_ENABLE = yes    # Use RGB Matrix (required for rev3 underglow)
RGBLIGHT_ENABLE = no       # Disable legacy RGBLIGHT to prevent right-half serial crash
WPM_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
VPATH  +=  keyboards/gboards/
SEND_STRING_ENABLE = yes
